## 标量

In [1]:
import numpy as np

In [2]:
a = np.array(4.0)

In [3]:
a.shape
# 标量没有形状

()

## 向量

In [4]:
x = np.arange(4)
x.shape

(4,)

In [5]:
len(x)

4

## 矩阵

In [6]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
A.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [8]:
A = np.arange(20).reshape(5, 4)
B = A.copy()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]]))

In [9]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

## 降维

In [10]:
a = np.arange(20).reshape(5,4)

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
a.sum()

190

In [13]:
a.sum(axis=0)

array([40, 45, 50, 55])

In [14]:
a.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [15]:
a.mean()

9.5

In [16]:
a.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [17]:
a.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

## 点积

In [18]:
x, y = np.arange(4), np.ones(4)

In [19]:
x,y,np.dot(x,y)

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0)

In [20]:
np.sum(x * y)

6.0

### 矩阵向量相乘

In [23]:
x = np.arange(20).reshape(5,4)

In [24]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
y = np.arange(4)

In [26]:
y

array([0, 1, 2, 3])

In [27]:
y.shape

(4,)

In [28]:
np.dot(x,y)

array([ 14,  38,  62,  86, 110])

### 矩阵矩阵相乘

In [30]:
B = np.ones(shape=(4,3))

In [31]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.dot(x,B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

## 范数(norm)

In [34]:
u = np.array([3, -4])
np.linalg.norm(u)

5.0

In [36]:
np.abs(u).sum()

7

In [37]:
np.linalg.norm(np.ones((4, 9)))

6.0