# 数据操作

## numpy

In [1]:
import numpy as np

In [2]:
arr = np.arange(16)

In [3]:
arr = arr.reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
a = arr[1,2]
a

6

In [5]:
b = arr[1,:]
b

array([4, 5, 6, 7])

In [6]:
c = arr[:,1]
c

array([ 1,  5,  9, 13])

In [7]:
d = arr[1:3, 1:]
d

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [8]:
# 每三行，每两列
e = arr[::3, ::2]  
e

array([[ 0,  2],
       [12, 14]])

## PyTorch